version: "3.8"

services:
  db:
    container_name: postgres
    image: postgres:9.6.18
    env_file:
      - .env
    ports:
      - 5432:5432

  mq:
    container_name: rabbitMQ
    image: rabbitmq:3.8-management
    env_file:
      - .env
    ports:
      - 5671:5671
      - 5672:5672
      - 25672:25672
      - 4369:4369
      - 15671:15671
      - 15672:15672